swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <math><foo-test><mi><li><table><foo-test><li></li></foo-test><a> <style> <! \${ </style> } <foo-b id="><img src onerror='alert(1)'>">hmm...</foo-b> </a></table></li></mi></foo-test></math>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
